default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS"){ 5 } %>
  timeout: 5000
  database: db/test.sqlite3

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default

production:
  <<: *default
  database: db/production.sqlite3